package api;

import java.util.ArrayList;

abstract class Item {
    int id;
    String name;
    float price;
    int calories;

    Item(int id) {
        // TODO Build query and populate instance variables
        // This constructor is to build an object from an item that exists
    }

    Item(String name, float price, int calories) {
        this.name = name;
        this.price = price;
        this.calories = calories;
    }

    int insert() {
        // TODO Insert this item into the database
        return 0;  // Return the item's ID (sequentially generated by DB)
    }

    static ArrayList<Item> parseItemList(String itemList) {
        ArrayList<Item> items = new ArrayList<>();
        String[] itemsAsStr = itemList.split(" ");
        for (String item : itemsAsStr) {
            char itemCode = item.charAt(0);
            int itemId = Integer.parseInt(item.substring(1));
            switch (itemCode) {
                case 'T':
                    items.add(new Topping(itemId));
                    break;
                case 'E':
                    items.add(new Entree(itemId));
                    break;
            }
        }
        return items;
    }
}