package api;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;

class Item {
    static final String id_column = "id";
    static final String name_column = "name";
    static final String price_column = "price";
    static final String calories_column = "calories";

    int id;
    String name;
    float price;
    int calories;

    Item(int id, String name, float price, int calories) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.calories = calories;
    }

    int insert() {
        // TODO Insert this item into the database
        return 0;  // Return the item's ID (sequentially generated by DB)
    }

    static ArrayList<Item> getAllItems(String itemType) throws SQLException {
        ArrayList<Item> items = new ArrayList<>();
        ArrayList<HashMap<String, String>> itemsDict = QueryBuilder.executeQuery(QueryBuilder.buildSelectionQuery(itemType, null));
        for (HashMap h : itemsDict) {
            Item i = new Item(Integer.parseInt((String) h.get(Item.id_column)),
                    (String) h.get(Item.name_column),
                    Float.parseFloat((String) h.get(Item.price_column)),
                    Integer.parseInt((String) h.get(Item.calories_column)));
            items.add(i);
        }
        return items;
    }

    static ArrayList<Item> parseItemList(String itemList) {
        ArrayList<Item> items = new ArrayList<>();
        String[] itemsAsStr = itemList.split(" ");
        for (String item : itemsAsStr) {
            char itemCode = item.charAt(0);
            int itemId = Integer.parseInt(item.substring(1));
            switch (itemCode) {
                case 'T':
                    //items.add(new Topping(itemId));
                    break;
                case 'E':
                    //items.add(new Entree(itemId));
                    break;
            }
        }
        return items;
    }
}