/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author Kevin
 */
public class PoSGUI extends javax.swing.JFrame {
    ArrayList<String> currentItems = new ArrayList<String>();
    /**
     * Creates new form PoSGUI
     */
    public PoSGUI() {
        initComponents();
    }
    
    public void update()
    {
        String orderText = "";
        //takes each order entry
        for(String orderEntry:currentItems) //"meal1,entree1 customization,side1,drink1"
        {
            //takes each item within order entry (incase of combo meals)
            String[] individualItems = orderEntry.split(","); //"meal1","entree1 customization","side1","drink1"
            if(individualItems.length != 1) //means it's a meal
            {
                orderText += "-" + individualItems[0] + "\n";
                for(int i = 1; i < individualItems.length; i++)//"entree1 cusomization"
                {
                    String[] customizations = individualItems[i].split(" "); //"entree1","custmoization"
                    //customizations[0] is the entree
                    orderText += "    -" + customizations[0] + "\n"; //entree1
                    for(int j = 1; j < customizations.length; j++)
                    {
                        orderText += "\t-" + customizations[i] + "\n";
                    }
                }               
            }
            else //TODO: in case not a meal
            {
            }
            orderText += "\n";
        }
        currentOrder.setText(orderText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        scrollPane1 = new java.awt.ScrollPane();
        scrollbar4 = new java.awt.Scrollbar();
        scrollbar3 = new java.awt.Scrollbar();
        scrollbar2 = new java.awt.Scrollbar();
        scrollbar1 = new java.awt.Scrollbar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        mealFrame = new javax.swing.JFrame();
        mealFrame.setVisible(false);
        currentMeal = new javax.swing.JLabel();
        entreeCustomize = new java.awt.Button();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        entreeLabel = new javax.swing.JLabel();
        customizations = new javax.swing.JLabel();
        sideLabel = new javax.swing.JLabel();
        drinkLabel = new javax.swing.JLabel();
        addItems = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        mealsButton = new java.awt.Button();
        entreesButton = new java.awt.Button();
        sidesButton = new java.awt.Button();
        drinksButton = new java.awt.Button();
        dessertsButton = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        deleteEntry = new javax.swing.JButton();
        priceCalories = new java.awt.TextArea();
        currentOrder = new java.awt.TextArea();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mealsPanel = new javax.swing.JPanel();
        meal1 = new javax.swing.JButton();
        meal2 = new javax.swing.JButton();
        meal3 = new javax.swing.JButton();
        meal4 = new javax.swing.JButton();
        meal5 = new javax.swing.JButton();
        entreesPanel = new javax.swing.JPanel();
        entreesPanel.setVisible(false);
        entree1 = new javax.swing.JButton();
        entree2 = new javax.swing.JButton();
        entree3 = new javax.swing.JButton();
        entree4 = new javax.swing.JButton();
        entree5 = new javax.swing.JButton();
        entree6 = new javax.swing.JButton();
        entree7 = new javax.swing.JButton();
        sidesPanel = new javax.swing.JPanel();
        side1 = new javax.swing.JButton();
        side2 = new javax.swing.JButton();
        side3 = new javax.swing.JButton();
        side4 = new javax.swing.JButton();
        drinksPanel = new javax.swing.JPanel();
        drink1 = new javax.swing.JButton();
        drink2 = new javax.swing.JButton();
        drink3 = new javax.swing.JButton();
        drink4 = new javax.swing.JButton();
        drink5 = new javax.swing.JButton();
        dessertsPanel = new javax.swing.JPanel();
        dessert1 = new javax.swing.JButton();
        dessert2 = new javax.swing.JButton();

        scrollPane1.add(scrollbar4);
        scrollPane1.add(scrollbar3);
        scrollPane1.add(scrollbar2);
        scrollPane1.add(scrollbar1);

        mealFrame.setAlwaysOnTop(true);
        mealFrame.setMinimumSize(new java.awt.Dimension(500, 600));
        mealFrame.setPreferredSize(new java.awt.Dimension(500, 600));

        currentMeal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        currentMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentMeal.setText("Meal1");

        entreeCustomize.setLabel("Customize");
        entreeCustomize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entreeCustomizeMouseClicked(evt);
            }
        });
        entreeCustomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreeCustomizeActionPerformed(evt);
            }
        });

        entreeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        entreeLabel.setText("entreeLabel");
        entreeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        customizations.setText("customizationsGoHere");
        customizations.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        sideLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        sideLabel.setText("sideLabel");
        sideLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        drinkLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        drinkLabel.setText("drinkLabel");
        drinkLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLayeredPane2.setLayer(entreeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(customizations, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(sideLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(drinkLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(customizations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinkLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(sideLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(entreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(customizations, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(entreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        addItems.setText("Add");
        addItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemsMouseClicked(evt);
            }
        });
        addItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mealFrameLayout = new javax.swing.GroupLayout(mealFrame.getContentPane());
        mealFrame.getContentPane().setLayout(mealFrameLayout);
        mealFrameLayout.setHorizontalGroup(
            mealFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealFrameLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entreeCustomize, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        mealFrameLayout.setVerticalGroup(
            mealFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mealFrameLayout.createSequentialGroup()
                        .addComponent(entreeCustomize, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PoS System");
        setPreferredSize(new java.awt.Dimension(1320, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1320, 720));

        mealsButton.setLabel("Meals");
        mealsButton.setMinimumSize(new java.awt.Dimension(80, 100));
        mealsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealsButtonMouseClicked(evt);
            }
        });
        mealsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsButtonActionPerformed(evt);
            }
        });

        entreesButton.setActionCommand("Entrees");
        entreesButton.setLabel("Entrees");
        entreesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entreesButtonMouseClicked(evt);
            }
        });
        entreesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreesButtonActionPerformed(evt);
            }
        });

        sidesButton.setLabel("Sides");
        sidesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidesButtonMouseClicked(evt);
            }
        });

        drinksButton.setLabel("Drinks");
        drinksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinksButtonMouseClicked(evt);
            }
        });

        dessertsButton.setLabel("Desserts");
        dessertsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dessertsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mealsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessertsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mealsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dessertsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteEntry.setText("jButton2");
        deleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEntryActionPerformed(evt);
            }
        });

        priceCalories.setPreferredSize(new java.awt.Dimension(20, 20));

        currentOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Proceed to Checkout >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(priceCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(currentOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mealsPanel.setMinimumSize(new java.awt.Dimension(860, 533));

        meal1.setText("Meal1");
        meal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meal1MouseClicked(evt);
            }
        });
        meal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal1ActionPerformed(evt);
            }
        });

        meal2.setText("Meal2");
        meal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meal2MouseClicked(evt);
            }
        });
        meal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal2ActionPerformed(evt);
            }
        });

        meal3.setText("Meal3");
        meal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meal3MouseClicked(evt);
            }
        });
        meal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal3ActionPerformed(evt);
            }
        });

        meal4.setText("Meal4");
        meal4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meal4MouseClicked(evt);
            }
        });
        meal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal4ActionPerformed(evt);
            }
        });

        meal5.setText("Meal5");
        meal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meal5MouseClicked(evt);
            }
        });
        meal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mealsPanelLayout = new javax.swing.GroupLayout(mealsPanel);
        mealsPanel.setLayout(mealsPanelLayout);
        mealsPanelLayout.setHorizontalGroup(
            mealsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mealsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mealsPanelLayout.createSequentialGroup()
                        .addComponent(meal1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meal2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(meal3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meal4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(meal5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        mealsPanelLayout.setVerticalGroup(
            mealsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mealsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meal1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meal2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meal3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meal4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(meal5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        entreesPanel.setEnabled(false);
        entreesPanel.setMinimumSize(new java.awt.Dimension(860, 533));

        entree1.setText("Entree1");
        entree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree1ActionPerformed(evt);
            }
        });

        entree2.setText("Entree2");
        entree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree2ActionPerformed(evt);
            }
        });

        entree3.setText("Entree3");
        entree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree3ActionPerformed(evt);
            }
        });

        entree4.setText("Entree4");
        entree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree4ActionPerformed(evt);
            }
        });

        entree5.setText("Entree5");
        entree5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree5ActionPerformed(evt);
            }
        });

        entree6.setText("Entree6");
        entree6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree6ActionPerformed(evt);
            }
        });

        entree7.setText("Entree7");
        entree7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entreesPanelLayout = new javax.swing.GroupLayout(entreesPanel);
        entreesPanel.setLayout(entreesPanelLayout);
        entreesPanelLayout.setHorizontalGroup(
            entreesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entreesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entreesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entreesPanelLayout.createSequentialGroup()
                        .addComponent(entree1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entree2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(entree3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entree4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entreesPanelLayout.createSequentialGroup()
                        .addComponent(entree5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entree6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(entree7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        entreesPanelLayout.setVerticalGroup(
            entreesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entreesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entreesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entree1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entree2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entree3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entree4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(entreesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entree5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entree6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entree7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        sidesPanel.setEnabled(false);
        sidesPanel.setMinimumSize(new java.awt.Dimension(860, 533));

        side1.setText("Side1");
        side1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side1ActionPerformed(evt);
            }
        });

        side2.setText("Side2");
        side2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2ActionPerformed(evt);
            }
        });

        side3.setText("Side3");
        side3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side3ActionPerformed(evt);
            }
        });

        side4.setText("Side4");
        side4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidesPanelLayout = new javax.swing.GroupLayout(sidesPanel);
        sidesPanel.setLayout(sidesPanelLayout);
        sidesPanelLayout.setHorizontalGroup(
            sidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(side1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(side2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(side3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(side4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        sidesPanelLayout.setVerticalGroup(
            sidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(side2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(side3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(side4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(505, Short.MAX_VALUE))
        );

        drinksPanel.setEnabled(false);
        drinksPanel.setMinimumSize(new java.awt.Dimension(860, 533));

        drink1.setText("Drink1");
        drink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drink1ActionPerformed(evt);
            }
        });

        drink2.setText("Drink2");
        drink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drink2ActionPerformed(evt);
            }
        });

        drink3.setText("Drink3");
        drink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drink3ActionPerformed(evt);
            }
        });

        drink4.setText("Drink4");
        drink4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drink4ActionPerformed(evt);
            }
        });

        drink5.setText("Drink5");
        drink5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drink5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinksPanelLayout = new javax.swing.GroupLayout(drinksPanel);
        drinksPanel.setLayout(drinksPanelLayout);
        drinksPanelLayout.setHorizontalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksPanelLayout.createSequentialGroup()
                        .addComponent(drink1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drink2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(drink3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drink4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(drink5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        drinksPanelLayout.setVerticalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drink1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drink5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        dessertsPanel.setEnabled(false);
        dessertsPanel.setMinimumSize(new java.awt.Dimension(860, 533));

        dessert1.setText("Dessert1");
        dessert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessert1ActionPerformed(evt);
            }
        });

        dessert2.setText("Dessert2");
        dessert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessert2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dessertsPanelLayout = new javax.swing.GroupLayout(dessertsPanel);
        dessertsPanel.setLayout(dessertsPanelLayout);
        dessertsPanelLayout.setHorizontalGroup(
            dessertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessertsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dessert1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dessert2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        dessertsPanelLayout.setVerticalGroup(
            dessertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessertsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dessertsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dessert1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessert2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(505, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(mealsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(entreesPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(sidesPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(drinksPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dessertsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entreesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mealsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(sidesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(drinksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dessertsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entreesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mealsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sidesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(drinksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dessertsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal2ActionPerformed

    private void meal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal3ActionPerformed

    private void meal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal4ActionPerformed

    private void meal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal1ActionPerformed

    private void mealsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealsButtonActionPerformed

    private void meal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entreesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entreesButtonMouseClicked
        //JOptionPane.showMessageDialog(this, "Hi");// TODO add your handling code here:
        mealsPanel.setVisible(false);
        entreesPanel.setVisible(true);
        sidesPanel.setVisible(false);
        drinksPanel.setVisible(false);
        dessertsPanel.setVisible(false);
        
        
    }//GEN-LAST:event_entreesButtonMouseClicked

    private void entreesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreesButtonActionPerformed
        //JOptionPane.showMessageDialog(this, "Hi2");// TODO add your handling code here:
    }//GEN-LAST:event_entreesButtonActionPerformed

    private void mealsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsButtonMouseClicked
        mealsPanel.setVisible(true);
        entreesPanel.setVisible(false);
        sidesPanel.setVisible(false);
        drinksPanel.setVisible(false);
        dessertsPanel.setVisible(false);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_mealsButtonMouseClicked

    private void sidesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidesButtonMouseClicked
        // TODO add your handling code here:
        mealsPanel.setVisible(false);
        entreesPanel.setVisible(false);
        sidesPanel.setVisible(true);
        drinksPanel.setVisible(false);
        dessertsPanel.setVisible(false);
    }//GEN-LAST:event_sidesButtonMouseClicked

    private void dessertsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessertsButtonMouseClicked
        // TODO add your handling code here:
        mealsPanel.setVisible(false);
        entreesPanel.setVisible(false);
        sidesPanel.setVisible(false);
        drinksPanel.setVisible(false);
        dessertsPanel.setVisible(true);
    }//GEN-LAST:event_dessertsButtonMouseClicked

    private void drinksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinksButtonMouseClicked
        // TODO add your handling code here:
        mealsPanel.setVisible(false);
        entreesPanel.setVisible(false);
        sidesPanel.setVisible(false);
        drinksPanel.setVisible(true);
        dessertsPanel.setVisible(false);
    }//GEN-LAST:event_drinksButtonMouseClicked

    private void entree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree1ActionPerformed

    private void entree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree2ActionPerformed

    private void entree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree3ActionPerformed

    private void entree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree4ActionPerformed

    private void entree5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree5ActionPerformed

    private void entree6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree6ActionPerformed

    private void entree7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree7ActionPerformed

    private void side1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_side1ActionPerformed

    private void side2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_side2ActionPerformed

    private void side3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_side3ActionPerformed

    private void side4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_side4ActionPerformed

    private void deleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEntryActionPerformed

    private void drink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drink1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drink1ActionPerformed

    private void drink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drink2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drink2ActionPerformed

    private void drink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drink3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drink3ActionPerformed

    private void drink4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drink4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drink4ActionPerformed

    private void drink5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drink5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drink5ActionPerformed

    private void dessert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessert1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dessert1ActionPerformed

    private void dessert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessert2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dessert2ActionPerformed

    private void meal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meal1MouseClicked
        // TODO add your handling code here:
        mealFrame.setVisible(true);
        currentMeal.setText("Meal1");
        entreeLabel.setText("Entree1");
        sideLabel.setText("Side2");
        drinkLabel.setText("Drink4");
    }//GEN-LAST:event_meal1MouseClicked

    private void meal5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meal5MouseClicked
        // TODO add your handling code here:
        mealFrame.setVisible(true);
        currentMeal.setText("Meal5");
        entreeLabel.setText("Entree5");
        sideLabel.setText("Side2");
        drinkLabel.setText("Drink5");
    }//GEN-LAST:event_meal5MouseClicked

    private void meal4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meal4MouseClicked
        // TODO add your handling code here:
        mealFrame.setVisible(true);
        currentMeal.setText("M4eal");
        entreeLabel.setText("Entree1");
        sideLabel.setText("Side2");
        drinkLabel.setText("Drink1");
    }//GEN-LAST:event_meal4MouseClicked

    private void meal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meal3MouseClicked
        // TODO add your handling code here:
        mealFrame.setVisible(true);
        currentMeal.setText("Meal3");
        entreeLabel.setText("Entree6");
        sideLabel.setText("Side3");
        drinkLabel.setText("Drink2");
    }//GEN-LAST:event_meal3MouseClicked

    private void meal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meal2MouseClicked
        // TODO add your handling code here:
        mealFrame.setVisible(true);
        currentMeal.setText("Meal2");
        entreeLabel.setText("Entree5");
        sideLabel.setText("Side4");
        drinkLabel.setText("Drink5");
    }//GEN-LAST:event_meal2MouseClicked

    private void entreeCustomizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entreeCustomizeMouseClicked
        // TODO add your handling code here:
        String text = entreeLabel.getText();
        System.out.println(text);
    }//GEN-LAST:event_entreeCustomizeMouseClicked

    private void entreeCustomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreeCustomizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entreeCustomizeActionPerformed

    private void addItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemsActionPerformed

    private void addItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemsMouseClicked
        // TODO add your handling code here:
        System.out.print(currentMeal.getText() + "," + entreeLabel.getText() + 
                " " + customizations.getText() + "," + sideLabel.getText() + ","
                + drinkLabel.getText());
        currentItems.add(currentMeal.getText() + "," + entreeLabel.getText() + 
                " " + customizations.getText() + "," + sideLabel.getText() + ","
                + drinkLabel.getText());
        update();
    }//GEN-LAST:event_addItemsMouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addItems;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel currentMeal;
    private java.awt.TextArea currentOrder;
    private javax.swing.JLabel customizations;
    private javax.swing.JButton deleteEntry;
    private javax.swing.JButton dessert1;
    private javax.swing.JButton dessert2;
    private java.awt.Button dessertsButton;
    private javax.swing.JPanel dessertsPanel;
    private javax.swing.JButton drink1;
    private javax.swing.JButton drink2;
    private javax.swing.JButton drink3;
    private javax.swing.JButton drink4;
    private javax.swing.JButton drink5;
    private javax.swing.JLabel drinkLabel;
    private java.awt.Button drinksButton;
    private javax.swing.JPanel drinksPanel;
    private javax.swing.JButton entree1;
    private javax.swing.JButton entree2;
    private javax.swing.JButton entree3;
    private javax.swing.JButton entree4;
    private javax.swing.JButton entree5;
    private javax.swing.JButton entree6;
    private javax.swing.JButton entree7;
    private java.awt.Button entreeCustomize;
    private javax.swing.JLabel entreeLabel;
    private java.awt.Button entreesButton;
    private javax.swing.JPanel entreesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton meal1;
    private javax.swing.JButton meal2;
    private javax.swing.JButton meal3;
    private javax.swing.JButton meal4;
    private javax.swing.JButton meal5;
    private javax.swing.JFrame mealFrame;
    private java.awt.Button mealsButton;
    private javax.swing.JPanel mealsPanel;
    private java.awt.TextArea priceCalories;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Scrollbar scrollbar2;
    private java.awt.Scrollbar scrollbar3;
    private java.awt.Scrollbar scrollbar4;
    private javax.swing.JButton side1;
    private javax.swing.JButton side2;
    private javax.swing.JButton side3;
    private javax.swing.JButton side4;
    private javax.swing.JLabel sideLabel;
    private java.awt.Button sidesButton;
    private javax.swing.JPanel sidesPanel;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
